made it data.table friendly
gloverd2/admr pull request #24
Opened 2020-08-27 14:12 UTC by gloverd2

2020-09-04 15:25 UTC, CRSlade1 commented
I've just tried it with a data.table with a factor variable and got an error.

This was enough to break it for me:
temp_df <- data.table(cat= c("a","b","c"))
expl_categorical(temp_df)
If that doesn't get the error, try declare it with temp_df[, cat := as.factor(cat)] first.

Another thing which is perhaps more minor but the order in which the columns are positioned is not necessarily great for numerics. i.e. (1, 11, 2, 3) rather than (1,2,3,11). My function prep_num_sort should address this, so you might want to use that in a sort before outputting. (Although that isn't pushed or approved yet).

2020-09-04 16:22 UTC, CRSlade1 commented on R/expl_categorical.R
> +  df[, sapply(df, is.factor)] <- sapply(df[, sapply(df,is.factor)], as.character)
This part here is where you get errors from data.table.
I've never used sapply like this numerous times in one line so this seemed quite confusing to me.

I tried to write this how I would and get something similar to this, which I didn't error on data.tables but was having other issues. After doing a bit of googling, I think this might be what you are after.

df[] <- lapply(df, function(x) if (is.factor(x)), as.character(x) else x))

2020-09-25 15:03 UTC, clementstross commented on R/expl_categorical.R
> +  df[, sapply(df, is.factor)] <- sapply(df[, sapply(df,is.factor)], as.character)
lets use something like mutate_if(is.factor, as.character)

2020-09-25 15:33 UTC, clementstross commented
Hi all I've added a test and a fix to this function and we can try and see how good we are at collaborative working

2020-09-30 08:20 UTC, gloverd2 commented on R/expl_categorical.R
> +  df[, sapply(df, is.factor)] <- sapply(df[, sapply(df,is.factor)], as.character)
This function was rebuilt using tidyverse ^^

2020-09-30 13:30 UTC, clementstross commented
Does this need a full review now? I think we've all gone over it but I can look at it again if you want @gloverd2.

2020-09-30 15:05 UTC, gloverd2 commented
@clementstross  yes if you dont mind

2020-09-30 15:26 UTC, clementstross requested changes
The tests fail. Can we get these to work maybe split them our and check each column as a vector? I will approve once it passes the tests

2020-09-30 15:26 UTC, clementstross commented on R/expl_categorical.R
>  #' n [Integer]: count of that level
Missing class col

2020-09-30 15:26 UTC, clementstross commented on R/expl_categorical.R
> +    mutate_if(is.factor, as.character) %>%
This line isn't needed anymore

2020-09-30 15:26 UTC, clementstross commented on R/expl_categorical.R
>  #'                 stringsAsFactors = FALSE)
Not important but I'd like an extra column of is.male = 0 or 1 just to show how it works for numeric too.

2020-10-01 09:10 UTC, gloverd2 commented on R/expl_categorical.R
> +    mutate_if(is.factor, as.character) %>%
I believe you are right sir

2020-10-01 09:10 UTC, gloverd2 commented on R/expl_categorical.R
>  #' n [Integer]: count of that level
done

2020-10-01 09:12 UTC, gloverd2 commented on R/expl_categorical.R
>  #'                 stringsAsFactors = FALSE)
will add

2020-10-01 09:13 UTC, gloverd2 commented
> The tests fail. Can we get these to work maybe split them our and check each column as a vector? I will approve once it passes the tests

Which test failed? and what was the reason? I have ran mine and they work fine except I just need to load (tidyr, dplyr, magrittr)

2020-10-01 14:32 UTC, CRSlade1 requested changes
Not sure if you wanted full review yet but here we go anyway.

Generally like the code. Looks pretty minimal but does what you ask for.
I'd have a think about how it looks to end users though, who potentially don't understand our code (I'm guilty of not doing this at times too).

2020-10-01 14:32 UTC, CRSlade1 commented on tests/testthat/test-expl_categorical.R
Don't know if you care about these but you haven't tested for infinites

2020-10-01 14:32 UTC, CRSlade1 commented on tests/testthat/test-expl_categorical.R
Also haven't tried NAs with numeric but I think your cases are probably sufficient.

2020-10-01 14:32 UTC, CRSlade1 commented on R/expl_categorical.R
>  #' sorted alphabetically.
I'm sure you're aware of this but also adding library() or require() calls at the start of the function to make sure you have the packages? Or are we saying that isn't needed due to calling packages needed upon initialisation of our package?

2020-10-01 17:48 UTC, gloverd2 commented on R/expl_categorical.R
> +
will do

2020-10-01 17:48 UTC, gloverd2 commented on R/expl_categorical.R
> +  p <- df %>%
kk

2020-10-01 17:49 UTC, gloverd2 commented on R/expl_categorical.R
> +  c <- df %>%
kk

2020-10-01 17:49 UTC, gloverd2 commented on R/expl_categorical.R
> +
will do

2020-10-01 17:55 UTC, gloverd2 commented on R/expl_categorical.R
>  #' sorted alphabetically.
discussion for next review, but when we move then on site we will need them. you shouldn't need them if it works as a proper package

2020-10-01 18:04 UTC, gloverd2 commented on R/expl_categorical.R
>  #' sorted alphabetically.
one solution which i believe to be OTT is to use <<packagename>>::function in front of all . but the fact that some functions will have greater priority because they were loaded first is a discussion worth having

2020-10-01 18:05 UTC, gloverd2 commented on tests/testthat/test-expl_categorical.R
infinits for parameters or within a dataset?
will add NA for numeric sure

2020-10-26 17:19 UTC, clementstross commented
@gloverd2 This still fails its tests for me. I have fixed it. See latest commit

2020-10-26 17:22 UTC, clementstross approved these changes

2020-10-27 15:01 UTC, gloverd2 commented
@CRSlade1 can we get a re-review on this please, requested changes prevents merging

2020-11-03 16:27 UTC, CRSlade1 approved these changes
Nice work, I tried but couldn't break it. 
Don't think you tested for this but it also works with logical type columns (can't think of many reasons why you would want this though).
Few very minor tweaks to make, then feel free to approve.

2020-11-03 16:27 UTC, CRSlade1 commented on R/expl_categorical.R
> +  if(length(var_info$var) < 1){return("no columns with fewer levels than either char.level or num.level")}
Would rather this is an if statement with a warning statement and an assert outside of it.
Open to other ways of doing this but I don't like outputting a string.

2020-11-03 16:27 UTC, CRSlade1 commented on R/expl_categorical.R
> +         #dplyr::mutate_if(is.character, as.factor) %>%
Is this line meant to be removed?

2020-11-04 14:15 UTC, merged