prep_char_num_sort, prep_num_band, expl_cond_dist_tbl
gloverd2/admr pull request #25
Opened 2020-09-07 12:37 UTC by CRSlade1

Finally sorted these functions out. Also didn't rebase as I think I now understand what to do to fix a conflict. 

Also would be curious to hear thoughts on leaving #TODO: statements at the end of functions that we don't think warrants raising an issue.

2020-09-07 14:52 UTC, clementstross commented on R/prep_char_num_sort.R
> +  #' @param unique Boolean (Default = FALSE) - Set this to true if you want unique sorted outputs after handling NAs.
I think the default should be true

2020-09-07 14:52 UTC, clementstross commented on R/prep_char_num_sort.R
> +  checkmate::assert_logical(char_decreasing,null.ok = TRUE)
len=1?

2020-09-07 14:52 UTC, clementstross commented on R/prep_num_band.R
> +  checkmate::assert_numeric(out_of_bands,any.missing = FALSE)
len=1

2020-09-07 14:52 UTC, clementstross commented on R/prep_char_num_sort.R
> +prep_char_num_sort <- function(array_to_sort, NA_val = NA, char_decreasing=FALSE, num_decreasing=FALSE, unique=FALSE){
This will still get file_10 and file_2 the wrong way round.

2020-09-07 14:52 UTC, clementstross commented on tests/testthat/test_prep_char_num_sort.R
> +  testthat::expect_equal(prep_char_num_sort(c(1,100,2,50),NA_val = "A"),c(1,2,50,100))
I don't like this behaviour. The output class changes depending on if there is an NA in the dataset. That could get very confusing.

2020-09-07 14:52 UTC, clementstross commented on tests/testthat/test_prep_num_band.R
> +  testthat::expect_equal(prep_num_band(c("A","B","1","2","C","5","6","7"),c(2,8)),c("A","B","2","2","C","8","8","8"))
I think we want a warning or an error here. I don't think letting people band with characters is what we want

2020-09-07 14:56 UTC, CRSlade1 commented on R/expl_cond_dist_tbl.R
> +expl_cond_dist_tbl <- function(main_var, cond_var, output_var="thin", NA_val="_NA", warn_high_band = 50L, err_high_band = 100L, verbose=TRUE){
Yep, above makes sense - didn't even realise I did that.

2020-09-07 15:01 UTC, CRSlade1 commented on R/expl_cond_dist_tbl.R
> +  sort_main <- prep_char_num_sort(unique(as.character(main_var)))
Think it's worth adding an option for including the order?

2020-09-07 15:03 UTC, CRSlade1 commented on R/expl_cond_dist_tbl.R
> +  output <- df %>%
I also don't like this variable name - might change this to thin_tbl

2020-09-07 15:04 UTC, CRSlade1 commented on R/expl_cond_dist_tbl.R
> +  wide_tbl <- data.frame(output) %>%
Good question. I don't know.

I think my reasoning at the time was that count is similar and it makes sense to make them look the same so you can compare but might as well just output wide_tbl

2020-09-07 15:16 UTC, CRSlade1 commented on R/prep_char_num_sort.R
> +prep_char_num_sort <- function(array_to_sort, NA_val = NA, char_decreasing=FALSE, num_decreasing=FALSE, unique=FALSE){
Yeah you're right. Hadn't even considered this but that's probably a case worth dealing with.  
Unsure how to go about this though because it also feels like I should generalise for the case of being able to deal with folder_1_subfolder_2_file_3 etc.. So split string into array of [chr, num, chr, num, chr, num], sort each of the groups of components and reassemble. Then there's also a whole element of what if not everything has the same structure. Could imagine a case of file2019_v1, file2019_v1.1 etc.

2020-09-07 15:20 UTC, CRSlade1 commented on R/prep_char_num_sort.R
> +  #' @param unique Boolean (Default = FALSE) - Set this to true if you want unique sorted outputs after handling NAs.
I initially had this as TRUE, as I could imagine this mainly being used for visualising results etc which is when I would expect it to be true. Arguably shouldn't even be including a unique function but only did so because of the case of potentially setting the NAs to the same as a pre-existing value.

2020-09-07 15:20 UTC, CRSlade1 commented on R/expl_cond_dist_tbl.R
> +  checkmate::assert_integerish(warn_high_band, any.missing = FALSE, lower = 2)
Yep

2020-09-07 15:32 UTC, CRSlade1 commented on tests/testthat/test_prep_num_band.R
> +  testthat::expect_equal(prep_num_band(c("A","B","1","2","C","5","6","7"),c(2,8)),c("A","B","2","2","C","8","8","8"))
Generally, I agree that this isn't great practice. I think there could however be benefit in Credit Data where you could need to check through loads of variables and most of them have C,M or T levels as well as numerics with potentially large ranges like (-300,500). I could imagine a case where it would be useful to band the levels together and plot them whilst also keeping the C,M and T fields to one side.

2020-09-07 15:37 UTC, CRSlade1 commented on tests/testthat/test_prep_char_num_sort.R
> +  testthat::expect_equal(prep_char_num_sort(c(1,100,2,50),NA_val = "A"),c(1,2,50,100))
I'm not sure what the best behaviour here would be. I agree that it is a weird thing to impute a series of numeric values to a character all of a sudden but you have had to manually specify that you want to impute to a character. Perhaps throwing a warning?

2020-09-08 07:08 UTC, clementstross commented on R/expl_cond_dist_tbl.R
> +expl_cond_dist_tbl <- function(main_var, cond_var, output_var="thin", NA_val="_NA", warn_high_band = 50L, err_high_band = 100L, verbose=TRUE){
I don't think it matters too much but we just need to decide if we care

2020-09-08 07:09 UTC, clementstross commented on R/expl_cond_dist_tbl.R
> +  wide_tbl <- data.frame(output) %>%
Again I don't think it really matters but it makes the code quite hard to follow.

2020-09-08 07:11 UTC, clementstross commented on R/expl_cond_dist_tbl.R
> +  sort_main <- prep_char_num_sort(unique(as.character(main_var)))
Same. You just want the prep_char_num_sort to sort by the factor order. I don't know if anyone other than me uses ordered factors much but it means you can keep useful labels and have %>% as.numeric() %>% as.matrix turn a human-readable data.frame into an xgboost DMatrix

2020-09-08 07:17 UTC, clementstross commented on R/prep_char_num_sort.R
> +prep_char_num_sort <- function(array_to_sort, NA_val = NA, char_decreasing=FALSE, num_decreasing=FALSE, unique=FALSE){
I agree. More effort than it is worth but I'd maybe leave a comment in the documentation. I'd also look at the case where it matches the regex string \w*\d+\w* and have it sort this case as it is easy. 

- check the string text is the same
- extract \d+
- sort these and use the order to sort the words

If you were really smart you could do the above as a function and call it from inside itself when needed and it could work on all cases

2020-09-08 07:20 UTC, clementstross commented on tests/testthat/test_prep_char_num_sort.R
> +  testthat::expect_equal(prep_char_num_sort(c(1,100,2,50),NA_val = "A"),c(1,2,50,100))
Always return a string? For the case of sorting numbers, why would we use your function? For the generic case for giving the order of factor levels, we probably want it to output a sting anyway as it is clearer

2020-09-08 07:21 UTC, clementstross commented on tests/testthat/test_prep_num_band.R
> +  testthat::expect_equal(prep_num_band(c("A","B","1","2","C","5","6","7"),c(2,8)),c("A","B","2","2","C","8","8","8"))
OK

2020-09-08 07:22 UTC, clementstross commented on R/expl_cond_dist_tbl.R
> +  output <- df %>%
I agree

2020-09-08 10:07 UTC, CRSlade1 commented on R/prep_char_num_sort.R
> +prep_char_num_sort <- function(array_to_sort, NA_val = NA, char_decreasing=FALSE, num_decreasing=FALSE, unique=FALSE){
Yeah, this is roughly what I was thinking. Did consider recursion, it's a lovely case for it - I'll have a short think about it but don't expect anything!

2020-09-08 10:08 UTC, CRSlade1 commented on tests/testthat/test_prep_char_num_sort.R
> +  testthat::expect_equal(prep_char_num_sort(c(1,100,2,50),NA_val = "A"),c(1,2,50,100))
Yep you're right - forgot we can ignore all numeric case. I'll just enforce strings out

2020-09-21 17:19 UTC, gloverd2 reviewed
i pulled the latest version on sladec2 and haven't been able to run the tests due to unique = TRUE & the test_expl_cond_dist_tbl giving tibble vs df

2020-09-21 17:19 UTC, gloverd2 commented on tests/testthat/test_prep_char_num_sort.R
> +  testthat::expect_equal(prep_char_num_sort(c(1,100,2,50,NA),NA_val = 2),c(1,2,2,50,100))
Error: prep_char_num_sort(c(1, 100, 2, 50, NA), NA_val = 2) not equal to c(1, 2, 2, 50, 100).
Lengths differ: 4 is not 5

unqiue issue again

2020-09-21 17:19 UTC, gloverd2 commented on tests/testthat/test_prep_char_num_sort.R
> +testthat::test_that("Testing properties",{
This testing segment is very long . where you have used comments you could be breaking them up . if it errors it returns the label of the test ("_Test failed_ 'Testing properties'"). so to break them up makes debugging much easier.

2020-09-21 17:19 UTC, gloverd2 commented on tests/testthat/test_expl_cond_dist_tbl.R
> +
not equal . returned a df and a tibble

2020-09-21 17:19 UTC, gloverd2 commented on tests/testthat/test_expl_cond_dist_tbl.R
> +
reoccuring theme across all tests?

2020-10-02 10:06 UTC, gloverd2 reviewed
don't add any other functions to this pull request.
prep num band and prep_char_num_sort are much closer to being approved

2020-11-05 12:59 UTC, CRSlade1 commented on tests/testthat/test_expl_cond_dist_tbl.R
> +
I need to adjust these. I was having issues getting this consistent. I think some of it is related to tidyverse version discrepancies between us

2020-11-06 14:13 UTC, clementstross requested changes
Fails the following test
prep_char_num_sort(c("0011","2","3","4","5", NA))

the output given is 
"_NA"  "2"    "3"    "4"    "5"    "1111"

if I remove the NA the problem goes away. I think the issue is in the regex statement

Also needs devtools::document() running check_all_identical.Rd doesn't exist

2020-11-06 14:13 UTC, clementstross commented on R/prep_num_band.R
> +#' Note: Banding is consistent with how Pricing view bands in rate tables.
I think I don't understand how pricing band rate tables. I hate this! I'm used to the other way around. Just to check if we have groups
0
1
2
3
I'd have thought 1.5 gets the rate of 1 but you're telling me it gets the rate of 2?

2020-11-06 14:13 UTC, clementstross commented on R/prep_num_band.R
> +  var_to_band_num <- var_to_band[!is.na(suppressWarnings(as.numeric(var_to_band)))]
Just assert that this is numeric. We don't want stray characters

2020-11-06 14:13 UTC, clementstross commented on R/prep_num_band.R
> +#' Bands are inclusive in the upper bound.
I'd like to make it such that this function and other banding function produced the same output. A list with "bins" and "labels" also have a choice to output the bin index or the bin label

2020-11-06 15:20 UTC, CRSlade1 commented on R/prep_char_num_sort.R
> +
Oops, forgot to take this out! Was using this for debugging

2020-11-06 15:23 UTC, CRSlade1 commented on R/check_all_identical.R
> +    # Check that list object 1 and list object 2 are identical. Use an and condition with that an identical check of all objects except 1.
It is in the description but sure will leave it here too

2020-11-06 15:29 UTC, CRSlade1 commented on R/expl_cond_dist_tbl.R
> +    dplyr::group_by(main_var, cond_var) %>%
Didn't know that was a thing

2020-11-06 15:41 UTC, CRSlade1 commented on R/prep_num_band.R
> +#' Note: Banding is consistent with how Pricing view bands in rate tables.
Yep. Don't hate the messenger. You'll see in a lot of rate tables that there is 999999 because "they" round up

2020-11-06 16:19 UTC, CRSlade1 commented on R/prep_char_num_sort.R
> +    first_nas <- c(if ((is.na(NA_val)) & sum(is.na(array)) > 0) {rep(NA_val,sum(is.na(array)))} else {NULL})
Unfortunately this doesn't work as ifelse executes row wise so does not accept array outputs.
E.g. ifelse(TRUE==TRUE, c(1,1,1), NA) gives just 1.

2020-11-06 16:42 UTC, CRSlade1 commented on R/expl_cond_dist_tbl.R
> +  if (length(sort_main) >= warn_high_band & verbose) {
There aren't the same. One of these is for main_var, one is for cond_var.

2020-11-06 16:43 UTC, CRSlade1 commented on R/expl_cond_dist_tbl.R
> +  if (length(sort_main) >= warn_high_band & verbose) {
Although having said that, I also enforced that the were the same length. I've since removed this as it now works without that constraint

2020-11-09 08:13 UTC, clementstross commented on R/prep_num_band.R
> +#' Note: Banding is consistent with how Pricing view bands in rate tables.
I hate that!

2020-11-09 08:15 UTC, clementstross commented on R/expl_cond_dist_tbl.R
> +  if (length(sort_main) >= warn_high_band & verbose) {
How does it work without constraints? I'd have thought they'd need to be the same length

2020-11-13 12:20 UTC, clementstross commented on tests/testthat/test_prep_char_num_sort.R
> +  testthat::expect_equal(prep_char_num_sort(c("C","M","T","-55555","-44444","-33333","0",NA),NA_val = "-1"),c("-1","C","M","T","-55555","-44444","-33333","0"))
These two tests can't be right. The order changes depending on NA_value="-1" vs NA_value=-1. Also I don't like All NAs being put at the start.

What happens with rep_char_num_sort(c("1","2","3",NA),NA_val = "2")
I think we want c("1", "2", "2", "3") i think yours gives c("2", "1",, "2", "3")

2020-11-24 15:11 UTC, CRSlade1 commented on R/prep_num_band.R
> +  var_to_band_num <- var_to_band[!is.na(suppressWarnings(as.numeric(var_to_band)))]
Discussed this in codebase conversation. Agreed that generally not great but for the sake of Credit Data, it makes everyone's lives easier.

2020-11-30 08:36 UTC, clementstross approved these changes

2020-11-30 10:17 UTC, merged