added feature importance
gloverd2/admr pull request #26
Opened 2020-09-14 14:52 UTC by clementstross

2020-09-21 16:35 UTC, gloverd2 reviewed
early review. does it need to be restricrted to xgboost? think Duncan has something that worked for other models too

2020-09-21 16:35 UTC, gloverd2 commented on R/feature_importance_permutation.R
> +#'                               target=data[[target]])
target should be specified or in ""

2020-09-21 16:35 UTC, gloverd2 commented on R/feature_importance_permutation.R
> +  if (is.null(weight)){weight <- rep(1, nrow(factors_df))}
Can somebody else check this too but for me the if statement runs on it's own without the else statement? I think becaue of the indentation.

2020-09-21 16:35 UTC, gloverd2 commented on tests/testthat/test_feature_importance_permutation.R
> +})
do we need decimal?

2020-09-21 16:35 UTC, gloverd2 commented on R/feature_importance_permutation.R
> +#'
the importance_sd column is NA. is this how it should be ? if its all NA should we drop it ?

2020-09-25 14:35 UTC, clementstross commented on R/feature_importance_permutation.R
> +#'                               target=data[[target]])
agree

2020-09-25 14:41 UTC, clementstross commented on R/feature_importance_permutation.R
> +#'
If nrounds is equal to 1 then it is NA i think this is probably what we want. I don't really mind though. I'll change the defaults so it happens less

2020-09-25 14:43 UTC, clementstross commented on R/feature_importance_permutation.R
> +  if (is.null(weight)){weight <- rep(1, nrow(factors_df))}
I have cleaned it up.

2020-10-01 18:24 UTC, gloverd2 commented on R/feature_importance_permutation.R
> +#'
no i am happy for it to be this way. have added a short line after importance_sd to clarify

2020-10-01 18:28 UTC, gloverd2 commented
What's the overall opinion on whether in tests we should clarify the parameter for each argument such that:
i.e function(parameter = user_input) or are we happy with function(user_input).
i find including the parameter is easier for me to read as a reviewer but i can understand things quickly get irrelevant and messy . Discuss

2020-10-01 18:31 UTC, gloverd2 approved these changes
approved with haste as i think it is very useful alongside the metrics. Im interested to know if its been use in practice?

2020-10-15 09:35 UTC, clementstross commented
@CRSlade1 Do you want a look at this? if not I'll merge either today or tomorrow

2020-11-06 19:26 UTC, CRSlade1 commented on R/feature_importance_permutation.R
> +      set.seed((seed * ii) + kk) # set seed
In cases where seed is low, you could end up with a large amount of collinearity.
i.e seed is 1, feature 1 goes from 2:11. seed is 1, feature 2 goes from 3:12.
Seed needs to be above length(model.features) for true independence.

2020-11-06 19:32 UTC, CRSlade1 commented on R/feature_importance_permutation.R
> +      set.seed((seed * ii) + kk) # set seed
I think this would also force seed to need to be positive. (Although you could just subtract instead if negative if you really wanted to allow that)

2020-11-06 19:35 UTC, CRSlade1 commented on R/feature_importance_permutation.R
> +  checkmate::assert_integerish(nrounds, len=1)
Must be positive

2020-11-06 19:36 UTC, CRSlade1 requested changes
Have some concerns about handling of seed and having biased permutations but think it's good except from that

2020-11-17 16:59 UTC, mdpead reviewed
Still in the middle of it, but saving just in case!

2020-11-17 16:59 UTC, mdpead commented on R/feature_importance_permutation.R
> +#'           :importance_mean - importance of factor
More changes from factor to feature

2020-11-17 16:59 UTC, mdpead commented on R/feature_importance_permutation.R
> +  # Get average prediction
This is the optimal / baseline prediction isn't it?

2020-11-17 16:59 UTC, mdpead commented on R/feature_importance_permutation.R
> +  }
Doesn't make a difference, but since the two `predicted <- ...` lines are the same, could pull this out of the if-else statement

2020-11-17 16:59 UTC, mdpead commented on R/feature_importance_permutation.R
> +      set.seed((((seed+length(model.features)) * ii) + kk)) # set seed
Maybe I'm missing something, but do we need to set a different seed for each loop? If we just set the seed at the beginning of the function, we will still get the same sequence of random numbers each time, and so the output of the function will be determinate.

2020-11-17 16:59 UTC, mdpead commented on R/feature_importance_permutation.R
> +#' @param model xgboost model
Just to check, we're expecting the xgboost model to be a final model with the optimal number of trees, rather than a trained sequence of trees where an optimal tree parameter is passed in?

2020-11-17 16:59 UTC, mdpead commented on R/feature_importance_permutation.R
> +    }
Given that this procedure is exactly the same as for the non-permuted data, would it make more sense to pass both the non-permuted data and each permutation through the same function?

2020-11-17 16:59 UTC, mdpead commented on R/feature_importance_permutation.R
> +  }
Could put this in the calculation on line 122 by just wrapping it in absolute function.

2020-11-17 16:59 UTC, mdpead commented on R/feature_importance_permutation.R
> +                            importance_mean=score_standard - (scores_permuted_ii %>% mean()),
I haven't used permutation importance before, but would expect it to be some relative measure from the `score_standard` here, say just divided through by `score_standard`. Or even coming out with a relative percentage of importance across all the features. Happy if this is the way it's usually calculated though.

2020-11-17 16:59 UTC, mdpead commented on R/feature_importance_permutation.R
> +    else{out_df <- rbind(out_df, out_df_ii)}
My R doesn't seem to like this section, but seems happier with if else is moved up to line 128...any ideas?

2020-11-18 13:18 UTC, clementstross commented on R/feature_importance_permutation.R
> +                            importance_mean=score_standard - (scores_permuted_ii %>% mean()),
I agree with you however I have copied the decision from
https://scikit-learn.org/stable/modules/generated/sklearn.inspection.permutation_importance.html#sklearn.inspection.permutation_importance

2020-11-18 13:32 UTC, mdpead commented on R/feature_importance_permutation.R
> +                            importance_mean=score_standard - (scores_permuted_ii %>% mean()),
Sweet, I'll bow to SKLearn.

2020-11-18 13:32 UTC, mdpead approved these changes
Looks good to me.

2020-11-25 17:05 UTC, CRSlade1 commented on R/feature_importance_permutation.R
> +  }
For anyone's future reference: Discussed but not true due to it being possible to have values worse than random.

2020-11-25 17:06 UTC, CRSlade1 commented on R/feature_importance_permutation.R
> +      set.seed((((seed+length(model.features)) * ii) + kk)) # set seed
For future reference: Discussed. Matt is right, it isn't needed but will be needed in 2D to isolate effects. Keeping here for continuity.

2020-11-25 17:07 UTC, CRSlade1 approved these changes
Thanks for making the changes asked for. Adding approval.

2020-11-26 10:45 UTC, merged