expl_diff_num
gloverd2/admr pull request #28
Opened 2020-10-04 15:16 UTC by gloverd2

A function that compares two df's and returns numerical differences. 
This is a very early draft. 
Tests still need to be done

2020-10-27 09:14 UTC, clementstross requested changes
Great function! I really like it! I think we just need a few more tests on df2 and then we're sorted. (then I'll pull down and run all the tests before approving)

2020-10-27 09:14 UTC, clementstross commented on R/expl_diff_num.R
> +    dplyr::rename('df1' = V2, 'df2' = V1) %>%
maybe let "df1" and "df2" be arguments? This would mean they could be set to "train" and "test"

2020-10-27 09:14 UTC, clementstross commented on R/expl_diff_num.R
> +    dplyr::mutate(diff = df1 - df2) %>%
can we also have percentage diff? (although be careful when the mean is 0)

2020-10-27 09:14 UTC, clementstross commented on R/expl_diff_num.R
> +                              na = ~sum(is.na(.))))
Can we have a proportion of na's. ~sum(is.na(.))/n()

2020-10-27 09:14 UTC, clementstross commented on tests/testthat/test-expl_diff_num.R
> +})
can you also check df2 and diff

2020-10-27 09:14 UTC, clementstross commented on tests/testthat/test-expl_diff_num.R
> +  testthat::expect_error(expl_diff_num())
Can you check values of df2 are checked

2020-10-27 09:39 UTC, clementstross commented on R/expl_diff_num.R
> +#' var [Character]: a character variable
I don't think this is right they are as rows

2020-11-06 11:31 UTC, gloverd2 commented on R/expl_diff_num.R
> +                              na = ~sum(is.na(.))))
done

2020-11-06 11:31 UTC, gloverd2 commented on R/expl_diff_num.R
> +    dplyr::rename('df1' = V2, 'df2' = V1) %>%
done

2020-11-06 11:44 UTC, gloverd2 commented on R/expl_diff_num.R
> +#' var [Character]: a character variable
good spot

2020-11-06 11:59 UTC, gloverd2 commented on R/expl_diff_num.R
> +    dplyr::mutate(diff = df1 - df2) %>%
done

2020-11-06 12:32 UTC, gloverd2 commented on tests/testthat/test-expl_diff_num.R
> +})
bish bash bosh done

2020-11-17 09:08 UTC, gloverd2 reviewed
good start could be better.

2020-11-17 09:08 UTC, gloverd2 commented on R/expl_diff_num.R
> +#'
is df1 and df2 good parameters?

2020-11-17 09:08 UTC, gloverd2 commented on R/expl_diff_num.R
> +#' diff: (df2 - df1)
what type is diff?

2020-11-18 16:31 UTC, battlerdj reviewed
Nice and neat, is it worth having a na.rm argument in the functions input to allow the user to decide whether na.rm should be true or false the metrics. Could be set to true as defult. Added some comments here and there too.

2020-11-18 16:31 UTC, battlerdj commented on tests/testthat/test-expl_diff_num.R
> +  testthat::expect_equal(length(setdiff(tolower(unique(expl_diff_num(df1, df2)$var)), tolower(names(df1)))), 0)
I'm assuming this checks the variables in the output are indeed in the original data frames. If so, do we need a second one for df2 here?

2020-11-19 10:03 UTC, ellenamoore reviewed
Expl_summary uses base:: but this doesn't. Might be a good idea to have this used consistently?

2020-11-19 15:42 UTC, gloverd2 commented on R/expl_diff_num.R
> +  # check that the two datasets have stuff in common
yeah agree

2020-11-19 15:42 UTC, gloverd2 commented on tests/testthat/test-expl_diff_num.R
> +  testthat::expect_error(expl_diff_num())
sure

2020-11-19 15:43 UTC, gloverd2 commented on tests/testthat/test-expl_diff_num.R
> +  testthat::expect_equal(length(setdiff(tolower(unique(expl_diff_num(df1, df2)$var)), tolower(names(df1)))), 0)
probably

2020-11-19 15:44 UTC, gloverd2 commented on R/expl_diff_num.R
> +    dplyr::select_if(is.double) %>%
hmmm.... i dont think so with base functions. i could be wrong but i feel base has priority

2020-11-19 15:44 UTC, gloverd2 commented on R/expl_diff_num.R
> +    dplyr::mutate_if(is.numeric, round, digits = 3) %>%
see above

2020-11-20 09:25 UTC, manoorn commented on R/expl_diff_num.R
> +#' giving information such as min, max, mean, std.
Does the description need to specify that the output returns 1 row per common variable i.e. returns numerical differences in the form of 1 row per variable that appears in both dataframe objects?

2020-11-20 09:27 UTC, manoorn reviewed
Slight alteration to the description to specify that only common variables are analysed.

2020-11-27 11:58 UTC, closed without merging