expl_diff_cat
gloverd2/admr pull request #29
Opened 2020-10-04 15:17 UTC by gloverd2

Compares 2 df's and returns the levels that are different for common variable names 
early draft 
tests need to be written

2020-10-27 08:54 UTC, clementstross requested changes
- I'd like some real test cases where we can see the output.
- I don't like the tolower() function being used as the default (this isn't normally the default in R)
- I'd also be interested in your thoughts of getting expl_categorical to do all the work. (this clearly doesn't matter as it is just a design choice)

2020-10-27 08:54 UTC, clementstross commented on R/expl_diff_cat.R
> +expl_diff_cat <- function(df, df2){
something odd is going on here with df and df1. From your docs, I believe this should be df1

2020-10-27 08:54 UTC, clementstross commented on R/expl_diff_cat.R
> +  commonvars <- intersect(tolower(names(df1)), tolower(names(df2)))
I'd give this under an option in the function input. eg ignore.case=TRUE

2020-10-27 08:54 UTC, clementstross commented on R/expl_diff_cat.R
> +  diff <- dplyr::setdiff(df2_pairs, df1_pairs)
A slightly subtle bug can occur here. If we are using tolower() then the output dif could have different have values for var which are not in either dataframe. see my example

```
df1 <- data.frame(PET= c(dragon, slug))
df2 <-  data.frame(PET= c(dragon, human))
```

your function will output
`data.frame(pet = c(slug))`
which might not be helpful as R is case sensitive.

Is this something you care about? (I think I do care but I can be convinced not to)

2020-10-27 08:54 UTC, clementstross commented on R/expl_diff_cat.R
> +    dplyr::rename_all(tolower) %>%
If you decide to use ignore.case option we'll need this like to be optional

2020-10-27 08:54 UTC, clementstross commented on R/expl_diff_cat.R
> +
What happens if there are common vars but they are all numeric? Do we want a message like the above one?

In these sorts of situations, I'd be tempted to throw a warning and output an empty data.frame with the correct columns. I think outputting a string like this could break stuff. Maybe something to chat about on a call?

2020-10-27 08:54 UTC, clementstross commented on tests/testthat/test-expl_diff_cat.R
> +})
Can we have an expected output version where we see/test exactly what the output looks like.

2020-10-27 08:54 UTC, clementstross commented on tests/testthat/test-expl_diff_cat.R
> +})
Can we see more testing around numeric values

2020-10-27 08:54 UTC, clementstross commented on R/expl_diff_cat.R
> +    dplyr::select_if(is.character) %>%
Do we want to think about keeping numeric values with <10 unique values?

2020-10-27 08:54 UTC, clementstross commented on R/expl_diff_cat.R
> +#' expl_diff_cat
Can we get this function to work off expl_categorical. Something like

```
expl_diff_cat <- function(df, df2, char.level=inf, num.level=10, option="in1not2"){

d1_cat <- expl_categorical(df=df1, char.level = char.level, num.level=num.level)
d2_cat <- expl_categorical(df=df2, char.level = char.level, num.level=num.level)

out _full<- full_join(d1_cat, d2_cat, by=c(var, level), suffix=c(".in1", ".in2"))
if (option="in1not2"){
out <- out _full %>% filter(!is.na(n.in2))
}else if (option="in2not1"){
out <- out _full %>% filter(!is.na(n.in1)) %>% select(####) %>% return()
}else if (option="in1and2"){
out <- out _full %>% filter(!is.na(n.in1) & !is.na(n.in2))  
}else if (option="all"){
out <- out _full
}

out %>% select(####) %>% return()

```

we now get a lot of extra useful information for free if we want it, you can have an option on the select(###)

what are your thoughts? Is this good or I'm trying to stop duplicated code

2020-10-27 09:33 UTC, gloverd2 commented on R/expl_diff_cat.R
> +expl_diff_cat <- function(df, df2){
i believe you are right

2020-10-27 09:34 UTC, gloverd2 commented on R/expl_diff_cat.R
> +  diff <- dplyr::setdiff(df2_pairs, df1_pairs)
I don't case either way but it should be solved by including an ignore.case argument

2020-10-27 09:36 UTC, gloverd2 commented on R/expl_diff_cat.R
> +
fair. will add to next agenda

2020-10-27 09:39 UTC, gloverd2 commented on R/expl_diff_cat.R
> +#' expl_diff_cat
it is the correct thing to do (to use expl_Categorical) but only when its approved & merged. 
otherwise i thought this was a nice one to look through and start writing tests etc. think of this as very weird pseudocode.

2020-10-27 09:43 UTC, clementstross commented on R/expl_diff_cat.R
> +#' expl_diff_cat
Ok well, I've just approved expl_Categorical

2020-11-06 12:51 UTC, gloverd2 commented on R/expl_diff_cat.R
> +  commonvars <- intersect(tolower(names(df1)), tolower(names(df2)))
done

2020-11-06 12:51 UTC, gloverd2 commented on R/expl_diff_cat.R
> +expl_diff_cat <- function(df, df2){
done

2020-11-06 12:55 UTC, gloverd2 commented on R/expl_diff_cat.R
> +    dplyr::rename_all(tolower) %>%
done

2020-11-06 12:57 UTC, gloverd2 commented on R/expl_diff_cat.R
> +
simialr to expl_categorical i have outputted a NULL df with a warning msg

2020-11-06 13:11 UTC, gloverd2 commented on tests/testthat/test-expl_diff_cat.R
> +})
done

2020-11-06 13:15 UTC, gloverd2 commented on R/expl_diff_cat.R
> +#' expl_diff_cat
yes we probably do

2020-11-10 12:34 UTC, veronicahorgan commented
df corrected to df1 twice in the function

2020-11-27 11:58 UTC, closed without merging