Issues with plotting functions
gloverd2/admr pull request #43
Opened 2020-11-03 08:51 UTC by clementstross

This pull request addresses
Issue #40 
Issue #38 
Issue #37 
Issue #36 

These were mostly identified on review by @CRSlade1, some were noticed by @clementstross himself. 

A large change was that the PrecisionRecall metrics now do NOT calculate the area under the curve. They have been aligned with sklearn.

The PDP and ALE plots now use a function for bucketing data.

2020-11-13 20:56 UTC, gloverd2 requested changes
1. are there tests for plotting numerical buckets?  

2. Optionally, can we think of a name for this function that agrees with the naming conventions of other functions i.e. prep_ ? 

3. I can see some changes have been made to remove certain packagename::'s from functions such as ggplot2::aes. I understand why it's been done, however it is causing errors if we test the package using RStudio. I do realise it doesnt stop us compiling the package however I feel as though using the test package function of RStudio benefits us in a lot of ways. (It picks up on undocumented params)

2020-11-13 20:56 UTC, gloverd2 commented on R/null_gini.R
> +    data <- data %>% filter(!is.na(actual) & !is.na(weight) & !is.na(predicted))
dplyr::filter

2020-11-13 20:56 UTC, gloverd2 commented on R/plot_PDP.R
> +                           by="join",
dplyr::mutate

2020-11-13 20:56 UTC, gloverd2 commented on R/plot_PDP.R
> +    plot.data <- full_join(plot.data.x %>% select(lower, upper, center, width) %>% mutate(join=1),
dplyr::full_join & dplyr::mutate

2020-11-13 20:56 UTC, gloverd2 commented on R/metric_ROC.R
> +metric_ROC <- function(actual, predicted, weight=NULL, na.rm=FALSE){
na.rm is not documented

2020-11-13 20:56 UTC, gloverd2 commented on R/null_gini.R
> +null_gini <- function(actual, predicted, weight=NULL, na.rm=FALSE){
na.rm is not documented

2020-11-13 20:56 UTC, gloverd2 commented on R/null_ROC.R
> +#' @export
na.rm is not documented

2020-11-16 08:41 UTC, clementstross commented
> 1. are there tests for plotting numerical buckets?
> 2. Optionally, can we think of a name for this function that agrees with the naming conventions of other functions i.e. prep_ ?
> 3. I can see some changes have been made to remove certain packagename::'s from functions such as ggplot2::aes. I understand why it's been done, however it is causing errors if we test the package using RStudio. I do realise it doesnt stop us compiling the package however I feel as though using the test package function of RStudio benefits us in a lot of ways. (It picks up on undocumented params)

Lets talk about names for this function in the next meeting. We might also want to make this function internal so not export it.

2020-11-25 11:46 UTC, gloverd2 approved these changes
I believe my latest changes were just to do with package namespaces. Otherwise I think these functions will be popular as we found in the example codebase doc they are pretty cool.

2020-11-25 12:58 UTC, merged