codebase example
gloverd2/admr pull request #48
Opened 2020-11-04 14:53 UTC by gloverd2

codebase example & change to namespace to allow use of expl_categorical in notebook

2020-11-04 16:08 UTC, clementstross requested changes
https://ourcodingclub.github.io/tutorials/writing-r-package/

can we move this to a notebook folder (or somewhere else sensible and add it to the .Rbuildignore).

* Can we have a better name than code
* Needs to have the suffix .ipynb for me to open it
* I haven't built the package so can't install it. Can we install it from the repo?
* Can we get the data in the repo? This is pretty normal to include example data. Loading it from file means a new person can't recreate the notebook
* I'd like some markdown text saying what each stage is trying to do. Have you used notebooks before or would you like me to show you how to do it?
* for ADMR::expl_categorical i'd add text saying this output could very easily be plotted
* Some of the lower cells don't have output saved.

Would a call help go over some of these points?

2020-11-04 16:40 UTC, gloverd2 commented
1.Can we have a better name than code - **example_script?**

2. Needs to have the suffix .ipynb for me to open it - **that is does, i very much didnt notice my type there**

3. I haven't built the package so can't install it. Can we install it from the repo? **Should be able to build from the Master Branch** 

4. Can we get the data in the repo? This is pretty normal to include example data. Loading it from file means a new person can't recreate the notebook. **I was just reading up on that. doesnt seem too difficult** 

5. I'd like some markdown text saying what each stage is trying to do. Have you used notebooks before or would you like me to show you how to do it? **to do list** 

6. for ADMR::expl_categorical i'd add text saying this output could very easily be plotted **can be included - todo list**

7. Some of the lower cells don't have output saved. - ** I didn't actually run them beforehand oops **

2020-11-06 15:18 UTC, clementstross approved these changes
I've made changes to this branch so my review means less. I'm happy that Dave and I have come to an agreement so I'm willing to approve and merge. @gloverd2 I'll leave it to you to decide if someone else should look at it or if we should merge

Although lets remove 
.ipynb_checkpoints/example_script-checkpoint.ipynb

2020-11-06 15:38 UTC, gloverd2 commented on codebase_example_script.Rmd
> +```{r process data, include=FALSE}
that was more for me to see what was going on at the time. 
I dont particularly think we need to show the names in the output.
but i dont mind if we do either.

2020-11-06 15:38 UTC, gloverd2 commented on codebase_example_script.Rmd
> +nhood_freq <- ADMR::encode_freq(data = hh_train$Neighborhood,
I think you have done this already?

2020-11-06 15:41 UTC, merged